/*
 * This file is generated by jOOQ.
 */
package com.happyghost.myjooqdemo.jooq;


import com.happyghost.myjooqdemo.jooq.tables.Build;
import com.happyghost.myjooqdemo.jooq.tables.Shop;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>test_demo</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.7"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BUILD_PRIMARY = Indexes0.BUILD_PRIMARY;
    public static final Index SHOP_PRIMARY = Indexes0.SHOP_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BUILD_PRIMARY = Internal.createIndex("PRIMARY", Build.BUILD, new OrderField[]{Build.BUILD.ID}, true);
        public static Index SHOP_PRIMARY = Internal.createIndex("PRIMARY", Shop.SHOP, new OrderField[]{Shop.SHOP.ID}, true);
    }
}
