/*
 * This file is generated by jOOQ.
*/
package com.happyghost.myjooqdemo.jooq;


import com.happyghost.myjooqdemo.jooq.tables.Shop;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test_demo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test_demo.shop</code>.
     */
    public static final Shop SHOP = com.happyghost.myjooqdemo.jooq.tables.Shop.SHOP;
}
