/*
 * This file is generated by jOOQ.
*/
package com.happyghost.myjooqdemo.jooq.tables.records;


import com.happyghost.myjooqdemo.jooq.tables.Shop;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopRecord extends UpdatableRecordImpl<ShopRecord> implements Record4<ULong, String, String, String> {

    private static final long serialVersionUID = 796245063;

    /**
     * Setter for <code>test_demo.shop.id</code>. 主键ID
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>test_demo.shop.id</code>. 主键ID
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>test_demo.shop.shop_name</code>. 店铺名称
     */
    public void setShopName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test_demo.shop.shop_name</code>. 店铺名称
     */
    public String getShopName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test_demo.shop.contact_name</code>. 联系人姓名
     */
    public void setContactName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test_demo.shop.contact_name</code>. 联系人姓名
     */
    public String getContactName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test_demo.shop.contact_phone</code>. 联系人手机号码
     */
    public void setContactPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test_demo.shop.contact_phone</code>. 联系人手机号码
     */
    public String getContactPhone() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<ULong, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<ULong, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Shop.SHOP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Shop.SHOP.SHOP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Shop.SHOP.CONTACT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Shop.SHOP.CONTACT_PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getShopName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContactName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getContactPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getShopName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContactName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContactPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopRecord value2(String value) {
        setShopName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopRecord value3(String value) {
        setContactName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopRecord value4(String value) {
        setContactPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopRecord values(ULong value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopRecord
     */
    public ShopRecord() {
        super(Shop.SHOP);
    }

    /**
     * Create a detached, initialised ShopRecord
     */
    public ShopRecord(ULong id, String shopName, String contactName, String contactPhone) {
        super(Shop.SHOP);

        set(0, id);
        set(1, shopName);
        set(2, contactName);
        set(3, contactPhone);
    }
}
